
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore
  namespace: jpetstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpetstore
  template:
    metadata:
      labels:
        app: jpetstore
    spec:
      containers:
        - name: jpetstore
          image: janivirtanen/petstore:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /jpetstore/
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /jpetstore/
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: jpetstore
  namespace: jpetstore
spec:
  selector:
    app: jpetstore
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
